apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crud-chart.fullname" . }}-secret
type: Opaque
data:
  ENCRYPTER_KEY: {{ .Values.service.appKey  | b64enc | quote }}
  APP_DB_CONNECTION: {{ printf "pgsql:host=%s;port=%s;dbname=%s" (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
  APP_DB_USER: {{ .Values.postgresql.postgresqlUsername  | b64enc | quote }}
  APP_DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword  | b64enc | quote }}