apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crud-chart.fullname" . }}
  labels:
  {{- include "crud-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "crud-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "crud-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: web
              containerPort: 8080
          env:
            - name: ENCRYPTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "crud-chart.fullname" . }}-secret
                  key: ENCRYPTER_KEY
            - name: APP_DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: {{ include "crud-chart.fullname" . }}-secret
                  key: APP_DB_CONNECTION
            - name: APP_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "crud-chart.fullname" . }}-secret
                  key: APP_DB_USER
            - name: APP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "crud-chart.fullname" . }}-secret
                  key: APP_DB_PASSWORD
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 5